name: Learning - ECR Workflow

on:
  workflow_dispatch:

jobs:
  checkout-and-inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect repository
        run: |
          echo "Current directory:"
          pwd

          echo "Repository files:"
          ls -la

       - name: Check Docker
        run: |
          docker version
          docker info
